TARGET = led_test1.bin

SRC = led_test1.cpp

BOARD=racer

WACKYLIB_DIR = ../../wackylib

include $(WACKYLIB_DIR)/Pacer.mk
include $(WACKYLIB_DIR)/Led.mk
# This must come last...
include ../../boards/board.mk




